export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const SIGN_UP_ERROR = 'SIGN_UP_ERROR'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'

export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'

export const GOT_USER_TIMERS = 'GOT_USER_TIMERS'
export const USER_TIMERS_ERROR = 'USER_TIMERS_ERROR'
export const SAVE_TIME_SUCCESS = 'SAVE_TIME_SUCCESS'

export const CLEAR_FORM_ERRORS = 'CLEAR_FORM_ERRORS'
